

subplot(2,5,1)
plot(u1)
ylabel('STYRSIGNAL');
xlabel('TID');
title('4');
subplot(2,5,2)
plot(u2)
ylabel('STYRSIGNAL');
xlabel('TID');
title('6');
subplot(2,5,3)
plot(u3)
ylabel('STYRSIGNAL');
xlabel('TID');
title('8');
subplot(2,5,4)
plot(u4)
ylabel('STYRSIGNAL');
xlabel('TID');
title('10');
subplot(2,5,5)
plot(u5)
ylabel('STYRSIGNAL');
xlabel('TID');
title('15');
subplot(2,5,6)
plot(y1)
ylabel('TEMP');
xlabel('TID');
title('4');
subplot(2,5,7)
plot(y2)
ylabel('TEMP');
xlabel('TID');
title('6');
subplot(2,5,8)
plot(y3)
ylabel('TEMP');
xlabel('TID');
title('8');
subplot(2,5,9)
plot(y4)
ylabel('TEMP');
xlabel('TID');
title('10');
subplot(2,5,10)
plot(y5)
ylabel('TEMP');
xlabel('TID');
title('15');